# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

minimal_mistakes_skin    : "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Pouya Zarbipour's Personal Website"
title_separator          : "-"
name                     : &name "Pouya Zarbipour"
description              : &description "Personal website showcasing research, publications, and portfolio."
url                      : https://pouyazarbipour.github.io
baseurl                  : ""
repository               : "pouyazarbipour/pouyazarbipour.github.io"
teaser                   : "profile.png"
breadcrumbs              : true
words_per_minute         : 160
future                   : true
read_more                : "enabled"
talkmap_link             : false

# Comments
comments:
  provider               : "disqus"
  disqus:
    shortname            : "pouyazarbipour-site"

# Staticman (optional)
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601"

# SEO Related
google_site_verification : "YOUR_GOOGLE_VERIFICATION_CODE"

# Social Sharing
twitter:
  username               : Pouyazarbipour
social:
  links: 
    - "https://scholar.google.com/citations?user=V5aIzssAAAAJ&hl=en&authuser=1"
    - "https://www.researchgate.net/profile/Pouya-Zarbipour"
    - "https://github.com/pouyazarbipour"
    - "https://www.linkedin.com/in/pouya-zarbipour"
    - "http://orcid.org/0000-0002-8024-9062"

# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          : "YOUR_TRACKING_ID"

# Site Author
author:
  name             : "Pouya Zarbipour"
  avatar           : "IMG_0386.JPG"
  bio              : "MSc in Civil Engineering with a focus on coastal and marine structures."
  location         : "Gilan, Iran"
  employer         : "Tarbiat Modares University"

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - README
  - node_modules
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  blogs:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
